### ISSUE TITLE
Doesn't handle a partially complete boot

### ISSUE THREAD

**Issue by dwijnand** [sbt/launcher#40]
I deleted `~/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.3-SNAPSHOT/io_2.12-1.1.0-SNAPSHOT.jar` (because I publishLocal'd a new snapshot) and I got:

```
java.lang.NoClassDefFoundError: sbt/io/FileFilter
	at sbt.xMain.run(Main.scala:73)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.io.FileFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by vanebea** [comment]
@dwijnand , did you ever get a solution to your problem, if you did kindly share. Am having the same problem.

**Comment by dwijnand** [comment]
I deleted the whole `~/.sbt/boot/scala-2.12.3/org.scala-sbt/sbt/1.0.3-SNAPSHOT` and sbt launcher redownloaded the snapshot from `~/.ivy2/local`.

**Comment by eed3si9n** [comment]
I don't know if handling a partial deletion of files in `~/.sbt/boot/` was supported by the original use case, so I wouldn't call this a bug.

Now that `reboot dev` cleans it up sort of automatically, I'd say this should be resolved won't fix.
