### ISSUE TITLE
java.lang.NoClassDefFoundError: sbt/io/FileFilter

### ISSUE THREAD

**Issue by vanebea** [sbt/launcher#57]
I am new to play framework... i have imported a project which i tried to run and the first error i receive is the **java.lang.NoClassDefFoundError: sbt/io/FileFilter**  any assistance will be highly appriciated.

java.lang.NoClassDefFoundError: sbt/io/FileFilter
        at sbt.xMain.run(Main.scala:74)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.io.FileFilter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
Error during sbt execution: java.lang.NoClassDefFoundError: sbt/io/FileFilter

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html

Without knowing exactly what you did (java version, sbt version, Play version, repro steps) it's not really possible to guess what's going on.
