### ISSUE TITLE
Launcher problems with JDK 11?

### ISSUE THREAD

**Issue by tobyweston** [sbt/launcher#99]
Does this line have a problem with newer versions of Java?

https://github.com/sbt/launcher/blob/605b67814f4f1a2ed6ddd46213ffec8e8e58ec2e/launcher-implementation/src/main/scala/xsbt/boot/Find.scala#L60

I get the following against 

```
java.lang.IllegalArgumentException: URI scheme is not "file"
at java.base/java.io.File.<init>(File.java:423)
at xsbt.boot.ResolvePaths$.apply(Find.scala:60)
at xsbt.boot.ResolvePaths$.$anonfun$apply$3(Find.scala:54)
at scala.Option.map(Option.scala:242)
at xsbt.boot.IvyOptions.map(LaunchConfiguration.scala:116)
at xsbt.boot.LaunchConfiguration.map(LaunchConfiguration.scala:78)
at xsbt.boot.ResolvePaths$.apply(Find.scala:54)
at xsbt.boot.Find.apply(Find.scala:45)
at xsbt.boot.Find$.apply(Find.scala:13)
at xsbt.boot.Launch$.parseConfiguration(Launch.scala:110)
at xsbt.boot.Launch$.parseAndInitializeConfig(Launch.scala:104)
at xsbt.boot.Launch$.apply(Launch.scala:33)
at xsbt.boot.Launch$.apply(Launch.scala:21)
at xsbt.boot.Boot$.runImpl(Boot.scala:78)
at xsbt.boot.Boot$.run(Boot.scala:73)
at xsbt.boot.Boot$.main(Boot.scala:21)
at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.IllegalArgumentException: URI scheme is not "file"

```

Massive guess from me. I'm running from within IDEA 2021.3.1 (which doesn't let me start the IDE in anything less than JDK 11). I'm speculating  that something has changed in Java's `File` to require a scheme...

```
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.9)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (213.5744.224)
    com.intellij.plugins.macoskeymap (213.5744.3)
    com.intellij.ideolog (203.0.27.0)
    org.jetbrains.plugins.hocon (2021.1.0)
    intellij.haskell (1.0.0-beta88)
    com.bashorov.mainMenuToggler (0.2.1)
    org.intellij.scala (2021.3.18)
    com.haulmont.jpab (2021.6.2-213)

```

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?
We run CI for sbt using JDK 8 and JDK 17 currently, and it used to be tested on JDK 11 for a long time.
